# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 10:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_username', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('paper_setter', 'Paper Setter'), ('moderator', 'Moderator'), ('examiner', 'Examiner'), ('scrutinizer', 'Scrutinizer'), ('head_examiner', 'Head Examiner')], max_length=30)),
                ('date_sent', models.DateField(default=datetime.datetime(2016, 7, 23, 10, 51, 3, 709497, tzinfo=utc))),
                ('appoimtment_termination_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('appointment_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('year_of_appointment', models.IntegerField(default=2016)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField(max_length=5)),
                ('application_form_cost', models.IntegerField(default=0, verbose_name='Cost of Application Form')),
                ('examination_fess_th', models.IntegerField(default=0, verbose_name='Examination fees for Theoretical papers')),
                ('examination_fess_pr', models.IntegerField(default=0, verbose_name='Examination fees for Practical papers')),
                ('centre_fees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('course', models.CharField(choices=[('commerce', 'M.Com'), ('business', 'M.Bm'), ('doctorate', 'Ph.D'), ('education', 'M.Ed'), ('post-doctoral', 'M.Phil'), ('science', 'M.Sc'), ('tech', 'M.Tech')], max_length=255, verbose_name='Award')),
                ('name_new', models.CharField(max_length=255)),
                ('challan_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('rb', 'Rajabazar'), ('sl', 'Saltlake'), ('h', 'Hazra'), ('cs', 'College Street'), ('b', 'Ballygunje')], max_length=255)),
                ('department_name', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(choices=[('ag', 'Agriculture'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('education', 'Education, Journalism & Library Science'), ('engg', 'Engineering & Technology'), ('arts', 'Fine Arts, Music and Home Science'), ('Law', 'Law')], default='engg', max_length=100)),
                ('dept_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(default=datetime.datetime(2016, 7, 23, 10, 51, 3, 706408, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_username', models.CharField(max_length=255)),
                ('date_of_appointment', models.DateField(default=datetime.datetime(2016, 7, 23, 10, 51, 3, 708616, tzinfo=utc))),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('appointment_year', models.IntegerField(default=2016)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter_username', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('date_of_appointment', models.DateField(null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('appointment_year', models.IntegerField(default=2016)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(blank=True, null=True, upload_to=b'')),
                ('subject_name', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(null=True)),
                ('full_marks', models.IntegerField(default=0)),
                ('time', models.CharField(default='3', max_length=2)),
                ('year_of_examination', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
                ('paper_setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.PaperSetter')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=5)),
                ('registration_id', models.CharField(max_length=20, unique=True)),
                ('semester', models.IntegerField(max_length=5)),
                ('paid', models.BooleanField(default=False)),
                ('course_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_new', models.CharField(max_length=255)),
                ('semester', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date_uploaded', models.DateField(default=datetime.datetime(2016, 7, 23, 10, 51, 3, 711419, tzinfo=utc))),
                ('is_approved', models.BooleanField(default=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UserStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('year_of_join', models.DateField()),
                ('is_activated', models.BooleanField(default=False)),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('designation', models.CharField(choices=[('hod', 'H.O.D'), ('teacher', 'Teacher'), ('controller', 'Controller'), ('student', 'Student')], max_length=255)),
            ],
            options={
                'verbose_name': 'CustomUser',
            },
        ),
        migrations.AddField(
            model_name='userstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Subject'),
        ),
        migrations.AddField(
            model_name='papersetter',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserStaff'),
        ),
        migrations.AddField(
            model_name='papersetter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Subject'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.UserStaff'),
        ),
        migrations.AddField(
            model_name='hod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserStaff'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Department'),
        ),
        migrations.AddField(
            model_name='challan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserStaff', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='questionpaper',
            unique_together=set([('subject_name', 'year_of_examination')]),
        ),
        migrations.AlterUniqueTogether(
            name='papersetter',
            unique_together=set([('subject_name', 'appointment_year'), ('setter_username', 'appointment_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='moderator',
            unique_together=set([('moderator_username', 'appointment_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='challan',
            unique_together=set([('course_name', 'semester')]),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('appointment_username', 'year_of_appointment', 'role')]),
        ),
    ]
