# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20160723_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papersetter',
            old_name='setter_username',
            new_name='setter_userid',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 54, 28, 320477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 54, 28, 317459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 54, 28, 319685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 54, 28, 322446, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='papersetter',
            unique_together=set([('subject_name', 'appointment_year'), ('setter_userid', 'appointment_year')]),
        ),
    ]
