# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20160723_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papersetter',
            old_name='username',
            new_name='setter_user_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 56, 1, 927939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 56, 1, 924922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 56, 1, 927129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 10, 56, 1, 929880, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='papersetter',
            unique_together=set([('subject_name', 'appointment_year'), ('setter_user_name', 'appointment_year')]),
        ),
    ]
