# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20160723_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 12, 51, 883908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 12, 51, 880812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 12, 51, 883131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 12, 51, 885872, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('appointment_username', 'year_of_appointment')]),
        ),
    ]
