# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20160723_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 17, 2, 557674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 17, 2, 554030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 17, 2, 556799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year_of_examination',
            field=models.IntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 23, 11, 17, 2, 559746, tzinfo=utc)),
        ),
    ]
