# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20160724_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 13, 23, 47, 907845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 13, 23, 47, 904825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Department'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.UserStaff'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 13, 23, 47, 907045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 13, 23, 47, 909723, tzinfo=utc)),
        ),
    ]
