# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_auto_20160724_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 38, 39, 946387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('hod', 'H.O.D'), ('teacher', 'Teacher')], max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Rajabazar', 'Rajabazar'), ('Saltlake', 'Saltlake'), ('Hazra', 'Hazra'), ('College Street', 'College Street'), ('Ballygunje', 'Ballygunje')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 38, 39, 943350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 38, 39, 945601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 38, 39, 948298, tzinfo=utc)),
        ),
    ]
