# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_auto_20160724_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 42, 8, 273045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('rb', 'Rajabazar'), ('sl', 'Saltlake'), ('h', 'Hazra'), ('cs', 'College Street'), ('b', 'Ballygunje')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 42, 8, 269904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 42, 8, 272210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2016, 7, 24, 19, 42, 8, 274951, tzinfo=utc)),
        ),
    ]
