# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20160820_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2017, 2, 20, 8, 3, 58, 766878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hod',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2017, 2, 20, 8, 3, 58, 763888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2017, 2, 20, 8, 3, 58, 766108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2017, 2, 20, 8, 3, 58, 768718, tzinfo=utc)),
        ),
    ]
